{
 "title": "Pool",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pool Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(shares_accepted_total[5m])",
     "legendFormat": "Pool Hashrate (5m)"
    },
    {
     "expr": "rate(shares_accepted_total[1h])",
     "legendFormat": "Pool Hashrate (1h)"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count((sum by (btcaddress) (rate(worker_shares_valid_total[5m])) > 0))",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "count((sum by (btcaddress, workername) (rate(worker_shares_valid_total[5m])) > 0))",
     "legendFormat": "Workers"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time() - start_time_seconds", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Best Share Difficulty",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "best_share", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hashrate Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (btcshort) (\n  label_replace(\n    worker_shares_valid_total,\n    \"btcshort\", \"$1...$2\", \"btcaddress\", \"^(....).*(........)$\"\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shares per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(shares_accepted_total[5m]) / 4294967296 / 300",
     "legendFormat": "Shares per second"
    }
   ]
  }
 ]
}