{
 "title": "Users and Workers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user_address",
    "label": "User's BTC Address",
    "query": {
     "query": "label_values(worker_shares_valid_total,btcaddress)"
    }
   },
   {
    "name": "workername",
    "label": "Worker Name",
    "query": {
     "query": "label_values(worker_shares_valid_total{btcaddress=\"$user_address\"},workername)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "User Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(btcaddress) (rate(worker_shares_valid_total{btcaddress=\"$user_address\"}[5m]))",
     "legendFormat": "Hashrate (5m)"
    },
    {
     "expr": "sum by(btcaddress) (rate(worker_shares_valid_total{btcaddress=\"$user_address\"}[1h]))",
     "legendFormat": "Hashrate (1h)"
    }
   ]
  },
  {
   "title": "Worker Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "repeat": "workername",
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "rate(worker_shares_valid_total{btcaddress=\"$user_address\", workername=\"$workername\"}[5m])",
     "legendFormat": "{{workername}} (5m)"
    },
    {
     "expr": "rate(worker_shares_valid_total{btcaddress=\"$user_address\", workername=\"$workername\"}[1h])",
     "legendFormat": "{{workername}} (1h)"
    }
   ]
  },
  {
   "title": "Highest Difficulty",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "repeat": "workername",
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "worker_best_share_ever{btcaddress=\"$user_address\", workername=\"$workername\"}",
     "legendFormat": "{{workername}}"
    }
   ]
  }
 ]
}