[store]
path = "./store.db"
background_task_frequency_hours = 24
pplns_ttl_days = 7

[stratum]
hostname = "0.0.0.0"
port = 3333
start_difficulty = 1
minimum_difficulty = 1
# The bitcoin address to use for first jobs when there are no shares
bootstrap_address = "<your bootstrap address here>"
# Any donation amount for developers to be sent to donation address. Default no donation.
# donation_address = "<your donation address here>"
# In basis points, 1% = 100 basis points. Default 0
# donation = 50
# Any fee amount for node/hydrapool provider to be sent to fee address. Default no fee.
# fee_address = "<your fee address here>"
# In basis points, 1% = 100 basis points. Default 0
# fee = 200
zmqpubhashblock = "tcp://127.0.0.1:28332"
# The network can be "main", "testnet4" or "signet"
network = "main"
version_mask = "1fffe000"
# The difficulty multiplier defines the window size for calculating payout proportions
# See https://github.com/p2poolv2/p2poolv2/wiki/Difficult-Multiplier on how to choose this
difficulty_multiplier = 1.0

[miner]
pubkey = "020202020202020202020202020202020202020202020202020202020202020202"

[bitcoinrpc]
# RPC credentials are loaded from env vars
url = "http://127.0.0.1:38332"
username = "p2pool"
password = "p2pool"

[logging]
# Specify a file path for the log file, if no log file is specified, console logging will be used
# file = "./logs/p2pool.log"
level = "debug"
# Pool, user and worker stats are dumped for consumption by stats tools
stats_dir = "./logs/stats"

[[tests]]
name = "integration"
path = "tests.main"

[api]
hostname = "0.0.0.0"
port = 46884
# Optional authentication credentials
auth_user = "hydrapool"
# auth_token is of the format salt:password-hmac. Use can hydrapool_cli gen-auth to generate a token.
auth_token = "781dbcddd95e53aabf940bd2c51f8360$a8f7ddfff9560d506da771096361ba75b9d4ed936f5c35373282f8a339ac1709"
