services:
  hydrapool:
    profiles: [hydrapool]
    build:
      context: ..
      dockerfile: docker/Dockerfile.hydrapool
    environment:
      - HYDRAPOOL_BITCOIN_NETWORK=${NETWORK:-signet}
      - HYDRAPOOL_BITCOIN_URL=bitcoind:${BTC_RPC_PORT:-38332}
      - HYDRAPOOL_STORE_PATH=/data/${NETWORK:-signet}
      - RUST_LOG=info
    command: /hydrapool/target/release/hydrapool --config=/hydrapool/config.toml
    volumes:
      - hydrapool_data:/data
    restart: unless-stopped
    ports:
      - "3333:3333"
      - "46884:46884" # API server port
    networks:
      - hydrapool_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
        
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ../prometheus/grafana/provisioning:/etc/grafana/provisioning:ro
      - ../prometheus/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  prometheus_data:
  grafana_data:
  hydrapool_data:

networks:
  hydrapool_network:
    driver: bridge
